### ISSUE TITLE
Node engine dependency 

### ISSUE THREAD

**Issue by WillSquire** [ethanneff/react-native-web-typescript#3]
Running `yarn` errors with `upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.12.0"`.

Workaround is to run `yarn --ignore-engines`

**Comment by ArThoX** [comment]
Same issue here. Could someone hint a dependencies fix ?

**Comment by colorgmi** [comment]
`yarn config set ignore-engines true`

Hi. I googled and found this solution; try it.

**Comment by ethanneff** [comment]
Thank you for reporting this. The `yarn.lock` I had was misconfigured. The latest code base has been updated so you will no longer see this error.
