### ISSUE TITLE
Use NatveBase UI Library

### ISSUE THREAD

**Issue by M144-Coder** [ethanneff/react-native-web-typescript#5]
Is there a way to add NativeBase UI library to this example as described in this link?
https://docs.nativebase.io/docs/GetStarted.html
 
I have noticed there is no webpack.config.js file in the root directory of the example.

**Comment by mohannad-mamo** [comment]
same question here, as I generally need to replace some packages so it work on the web version.

Update:
- as far as I was able to find, seems with react-scripts you can not have your own config for webpack. to have them, you must eject the project from react-scripts, but it is not reversible.
check this page:
https://stackoverflow.com/questions/48395804/where-is-create-react-app-webpack-config-and-files

- This package seems to solve that issue by wrapping the react-scripts with it:
https://github.com/facetothefate/webpack-conf-react-scripts

**Comment by Ringert** [comment]
I'm successfully using NativeBase UI with react-native-web-typescript. It's a bit tricky, but with [react-app-rewired](https://github.com/timarney/react-app-rewired) you're able to override/add some webpack configuration used by react-script.

here a boilerplate: https://github.com/Ringert/react-native-web-typescript-native-base-ui

```
1. run yarn install
2. edit node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js like mentioned in https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/155#issuecomment-484427924 (please read carefully)
3. edit app.json and Config->index.tsx "name" (have to be the same "name" value)
4. run react-native eject
5. run react-native link
```
