### ISSUE TITLE
react-navigation integration

### ISSUE THREAD

**Issue by vitalyiegorov** [ethanneff/react-native-web-typescript#55]
Hi @henninghall @ethanneff, your repo is awesome, thanks a lot, due to the lack of information regarding the integration of react-native-web into the react-native-cli project. 

Could you please help me with intergration of react-navigation? Right now adding it and rendering StackNavigator ends with a compilation error: 
```
SyntaxError: react-native-web-typescript/node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js: Unexpected token (33:11)
```

I am aware of this [issue](https://github.com/react-navigation/react-navigation/issues/6155)

**Comment by ethanneff** [comment]
The latest release has a react-navigation integration https://github.com/ethanneff/react-native-web-typescript/releases/tag/1.2.0
